# Project: sturm
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"E:/u3/program/Dev-CppPortable/App/devcpp/lib" -L"D:/libs/freeglut/lib" -L"D:/libs/glew-1.8.0/lib" -lmingw32 -lfreeglut -lopengl32 -lglu32 -lglew32  
INCS =  -I"E:/u3/program/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"E:/u3/program/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"E:/u3/program/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"E:/u3/program/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"E:/u3/program/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"E:/u3/program/Dev-CppPortable/App/devcpp/include"  -I"D:/libs/freeglut/include"  -I"D:/libs/glew-1.8.0/include" 
BIN  = sturm.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before sturm.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "sturm.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
